/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Address */
    Address: {
      /**
       * Line1
       * @default null
       */
      line1: string | null
      /**
       * Line2
       * @default null
       */
      line2: string | null
      /**
       * Postal Code
       * @default null
       */
      postal_code: string | null
      /**
       * City
       * @default null
       */
      city: string | null
      /**
       * State
       * @default null
       */
      state: string | null
      /**
       * CountryAlpha2
       * @example US
       * @example SE
       * @example FR
       * @enum {string}
       */
      country:
        | 'AD'
        | 'AE'
        | 'AF'
        | 'AG'
        | 'AI'
        | 'AL'
        | 'AM'
        | 'AO'
        | 'AQ'
        | 'AR'
        | 'AS'
        | 'AT'
        | 'AU'
        | 'AW'
        | 'AX'
        | 'AZ'
        | 'BA'
        | 'BB'
        | 'BD'
        | 'BE'
        | 'BF'
        | 'BG'
        | 'BH'
        | 'BI'
        | 'BJ'
        | 'BL'
        | 'BM'
        | 'BN'
        | 'BO'
        | 'BQ'
        | 'BR'
        | 'BS'
        | 'BT'
        | 'BV'
        | 'BW'
        | 'BY'
        | 'BZ'
        | 'CA'
        | 'CC'
        | 'CD'
        | 'CF'
        | 'CG'
        | 'CH'
        | 'CI'
        | 'CK'
        | 'CL'
        | 'CM'
        | 'CN'
        | 'CO'
        | 'CR'
        | 'CU'
        | 'CV'
        | 'CW'
        | 'CX'
        | 'CY'
        | 'CZ'
        | 'DE'
        | 'DJ'
        | 'DK'
        | 'DM'
        | 'DO'
        | 'DZ'
        | 'EC'
        | 'EE'
        | 'EG'
        | 'EH'
        | 'ER'
        | 'ES'
        | 'ET'
        | 'FI'
        | 'FJ'
        | 'FK'
        | 'FM'
        | 'FO'
        | 'FR'
        | 'GA'
        | 'GB'
        | 'GD'
        | 'GE'
        | 'GF'
        | 'GG'
        | 'GH'
        | 'GI'
        | 'GL'
        | 'GM'
        | 'GN'
        | 'GP'
        | 'GQ'
        | 'GR'
        | 'GS'
        | 'GT'
        | 'GU'
        | 'GW'
        | 'GY'
        | 'HK'
        | 'HM'
        | 'HN'
        | 'HR'
        | 'HT'
        | 'HU'
        | 'ID'
        | 'IE'
        | 'IL'
        | 'IM'
        | 'IN'
        | 'IO'
        | 'IQ'
        | 'IR'
        | 'IS'
        | 'IT'
        | 'JE'
        | 'JM'
        | 'JO'
        | 'JP'
        | 'KE'
        | 'KG'
        | 'KH'
        | 'KI'
        | 'KM'
        | 'KN'
        | 'KP'
        | 'KR'
        | 'KW'
        | 'KY'
        | 'KZ'
        | 'LA'
        | 'LB'
        | 'LC'
        | 'LI'
        | 'LK'
        | 'LR'
        | 'LS'
        | 'LT'
        | 'LU'
        | 'LV'
        | 'LY'
        | 'MA'
        | 'MC'
        | 'MD'
        | 'ME'
        | 'MF'
        | 'MG'
        | 'MH'
        | 'MK'
        | 'ML'
        | 'MM'
        | 'MN'
        | 'MO'
        | 'MP'
        | 'MQ'
        | 'MR'
        | 'MS'
        | 'MT'
        | 'MU'
        | 'MV'
        | 'MW'
        | 'MX'
        | 'MY'
        | 'MZ'
        | 'NA'
        | 'NC'
        | 'NE'
        | 'NF'
        | 'NG'
        | 'NI'
        | 'NL'
        | 'NO'
        | 'NP'
        | 'NR'
        | 'NU'
        | 'NZ'
        | 'OM'
        | 'PA'
        | 'PE'
        | 'PF'
        | 'PG'
        | 'PH'
        | 'PK'
        | 'PL'
        | 'PM'
        | 'PN'
        | 'PR'
        | 'PS'
        | 'PT'
        | 'PW'
        | 'PY'
        | 'QA'
        | 'RE'
        | 'RO'
        | 'RS'
        | 'RU'
        | 'RW'
        | 'SA'
        | 'SB'
        | 'SC'
        | 'SD'
        | 'SE'
        | 'SG'
        | 'SH'
        | 'SI'
        | 'SJ'
        | 'SK'
        | 'SL'
        | 'SM'
        | 'SN'
        | 'SO'
        | 'SR'
        | 'SS'
        | 'ST'
        | 'SV'
        | 'SX'
        | 'SY'
        | 'SZ'
        | 'TC'
        | 'TD'
        | 'TF'
        | 'TG'
        | 'TH'
        | 'TJ'
        | 'TK'
        | 'TL'
        | 'TM'
        | 'TN'
        | 'TO'
        | 'TR'
        | 'TT'
        | 'TV'
        | 'TW'
        | 'TZ'
        | 'UA'
        | 'UG'
        | 'UM'
        | 'US'
        | 'UY'
        | 'UZ'
        | 'VA'
        | 'VC'
        | 'VE'
        | 'VG'
        | 'VI'
        | 'VN'
        | 'VU'
        | 'WF'
        | 'WS'
        | 'YE'
        | 'YT'
        | 'ZA'
        | 'ZM'
        | 'ZW'
    }
    Benefit:
      | components['schemas']['BenefitCustom']
      | components['schemas']['BenefitDiscord']
      | components['schemas']['BenefitGitHubRepository']
      | components['schemas']['BenefitDownloadables']
      | components['schemas']['BenefitLicenseKeys']
      | components['schemas']['BenefitMeterCredit']
      | components['schemas']['BenefitCourseAccess']
    /**
     * BenefitCourseAccess
     * @description A benefit of type `course_access`.
     *
     *     Created by the courses module on course publish so that purchasing
     *     the underlying product triggers a CourseEnrollment via the standard
     *     benefit-grant pipeline. Not user-managed: `selectable=false`,
     *     `deletable=false`.
     */
    BenefitCourseAccess: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the benefit.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Type
       * @constant
       */
      type: 'course_access'
      /**
       * Description
       * @description The description of the benefit.
       */
      description: string
      /**
       * Selectable
       * @description Whether the benefit is selectable when creating a product.
       */
      selectable: boolean
      /**
       * Deletable
       * @description Whether the benefit is deletable.
       */
      deletable: boolean
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the benefit.
       */
      organization_id: string
      metadata: components['schemas']['MetadataOutputType']
      properties: components['schemas']['BenefitCourseAccessProperties']
    }
    /**
     * BenefitCourseAccessProperties
     * @description Properties for a benefit of type `course_access`.
     *
     *     The benefit is internal plumbing — it's created automatically when a
     *     course is published, and its grant handler enrolls the buying
     *     customer in the course. The only configuration is which course it
     *     points at.
     */
    BenefitCourseAccessProperties: {
      /** Course Id */
      course_id: string
    }
    /**
     * BenefitCustom
     * @description A benefit of type `custom`.
     *
     *     Use it to grant any kind of benefit that doesn't fit in the other types.
     */
    BenefitCustom: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the benefit.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Type
       * @constant
       */
      type: 'custom'
      /**
       * Description
       * @description The description of the benefit.
       */
      description: string
      /**
       * Selectable
       * @description Whether the benefit is selectable when creating a product.
       */
      selectable: boolean
      /**
       * Deletable
       * @description Whether the benefit is deletable.
       */
      deletable: boolean
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the benefit.
       */
      organization_id: string
      metadata: components['schemas']['MetadataOutputType']
      properties: components['schemas']['BenefitCustomProperties']
    }
    /**
     * BenefitCustomProperties
     * @description Properties for a benefit of type `custom`.
     */
    BenefitCustomProperties: {
      /** Note */
      note: (string | null) | null
    }
    /**
     * BenefitDiscord
     * @description A benefit of type `discord`.
     *
     *     Use it to automatically invite your backers to a Discord server.
     */
    BenefitDiscord: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the benefit.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Type
       * @constant
       */
      type: 'discord'
      /**
       * Description
       * @description The description of the benefit.
       */
      description: string
      /**
       * Selectable
       * @description Whether the benefit is selectable when creating a product.
       */
      selectable: boolean
      /**
       * Deletable
       * @description Whether the benefit is deletable.
       */
      deletable: boolean
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the benefit.
       */
      organization_id: string
      metadata: components['schemas']['MetadataOutputType']
      properties: components['schemas']['BenefitDiscordProperties']
    }
    /**
     * BenefitDiscordProperties
     * @description Properties for a benefit of type `discord`.
     */
    BenefitDiscordProperties: {
      /**
       * Guild Id
       * @description The ID of the Discord server.
       */
      guild_id: string
      /**
       * Role Id
       * @description The ID of the Discord role to grant.
       */
      role_id: string
      /**
       * Kick Member
       * @description Whether to kick the member from the Discord server on revocation.
       */
      kick_member: boolean
      /** Guild Token */
      readonly guild_token: string
    }
    /** BenefitDownloadables */
    BenefitDownloadables: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the benefit.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Type
       * @constant
       */
      type: 'downloadables'
      /**
       * Description
       * @description The description of the benefit.
       */
      description: string
      /**
       * Selectable
       * @description Whether the benefit is selectable when creating a product.
       */
      selectable: boolean
      /**
       * Deletable
       * @description Whether the benefit is deletable.
       */
      deletable: boolean
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the benefit.
       */
      organization_id: string
      metadata: components['schemas']['MetadataOutputType']
      properties: components['schemas']['BenefitDownloadablesProperties']
    }
    /** BenefitDownloadablesProperties */
    BenefitDownloadablesProperties: {
      /** Archived */
      archived: {
        [key: string]: boolean
      }
      /** Files */
      files: string[]
    }
    /**
     * BenefitGitHubRepository
     * @description A benefit of type `github_repository`.
     *
     *     Use it to automatically invite your backers to a private GitHub repository.
     */
    BenefitGitHubRepository: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the benefit.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Type
       * @constant
       */
      type: 'github_repository'
      /**
       * Description
       * @description The description of the benefit.
       */
      description: string
      /**
       * Selectable
       * @description Whether the benefit is selectable when creating a product.
       */
      selectable: boolean
      /**
       * Deletable
       * @description Whether the benefit is deletable.
       */
      deletable: boolean
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the benefit.
       */
      organization_id: string
      metadata: components['schemas']['MetadataOutputType']
      properties: components['schemas']['BenefitGitHubRepositoryProperties']
    }
    /**
     * BenefitGitHubRepositoryProperties
     * @description Properties for a benefit of type `github_repository`.
     */
    BenefitGitHubRepositoryProperties: {
      /**
       * Repository Owner
       * @description The owner of the repository.
       * @example polarsource
       */
      repository_owner: string
      /**
       * Repository Name
       * @description The name of the repository.
       * @example private_repo
       */
      repository_name: string
      /**
       * Permission
       * @description The permission level to grant. Read more about roles and their permissions on [GitHub documentation](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role).
       * @enum {string}
       */
      permission: 'pull' | 'triage' | 'push' | 'maintain' | 'admin'
    }
    /** BenefitLicenseKeyActivationProperties */
    BenefitLicenseKeyActivationProperties: {
      /** Limit */
      limit: number
      /** Enable Customer Admin */
      enable_customer_admin: boolean
    }
    /** BenefitLicenseKeyExpirationProperties */
    BenefitLicenseKeyExpirationProperties: {
      /** Ttl */
      ttl: number
      /**
       * Timeframe
       * @enum {string}
       */
      timeframe: 'year' | 'month' | 'day'
    }
    /** BenefitLicenseKeys */
    BenefitLicenseKeys: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the benefit.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Type
       * @constant
       */
      type: 'license_keys'
      /**
       * Description
       * @description The description of the benefit.
       */
      description: string
      /**
       * Selectable
       * @description Whether the benefit is selectable when creating a product.
       */
      selectable: boolean
      /**
       * Deletable
       * @description Whether the benefit is deletable.
       */
      deletable: boolean
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the benefit.
       */
      organization_id: string
      metadata: components['schemas']['MetadataOutputType']
      properties: components['schemas']['BenefitLicenseKeysProperties']
    }
    /** BenefitLicenseKeysProperties */
    BenefitLicenseKeysProperties: {
      /** Prefix */
      prefix: string | null
      expires:
        | components['schemas']['BenefitLicenseKeyExpirationProperties']
        | null
      activations:
        | components['schemas']['BenefitLicenseKeyActivationProperties']
        | null
      /** Limit Usage */
      limit_usage: number | null
    }
    /**
     * BenefitMeterCredit
     * @description A benefit of type `meter_unit`.
     *
     *     Use it to grant a number of units on a specific meter.
     */
    BenefitMeterCredit: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the benefit.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Type
       * @constant
       */
      type: 'meter_credit'
      /**
       * Description
       * @description The description of the benefit.
       */
      description: string
      /**
       * Selectable
       * @description Whether the benefit is selectable when creating a product.
       */
      selectable: boolean
      /**
       * Deletable
       * @description Whether the benefit is deletable.
       */
      deletable: boolean
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the benefit.
       */
      organization_id: string
      metadata: components['schemas']['MetadataOutputType']
      properties: components['schemas']['BenefitMeterCreditProperties']
    }
    /**
     * BenefitMeterCreditProperties
     * @description Properties for a benefit of type `meter_unit`.
     */
    BenefitMeterCreditProperties: {
      /** Units */
      units: number
      /** Rollover */
      rollover: boolean
      /**
       * Meter Id
       * Format: uuid4
       */
      meter_id: string
    }
    /** ClientInvoiceEmail */
    ClientInvoiceEmail: {
      /**
       * Template
       * @default client_invoice
       * @constant
       */
      template: 'client_invoice'
      props: components['schemas']['ClientInvoiceEmailProps']
    }
    /** ClientInvoiceEmailLineItem */
    ClientInvoiceEmailLineItem: {
      /** Description */
      description: string
      /** Quantity */
      quantity: number
      /** Amount */
      amount: number
    }
    /** ClientInvoiceEmailProps */
    ClientInvoiceEmailProps: {
      /** Email */
      email: string
      /** Organization Name */
      organization_name: string
      /**
       * Organization Avatar Url
       * @default null
       */
      organization_avatar_url: string | null
      /** Customer Name */
      customer_name: string
      /** Invoice Id */
      invoice_id: string
      /** Due Date */
      due_date: string | null
      /** Currency */
      currency: string
      /** Line Items */
      line_items: components['schemas']['ClientInvoiceEmailLineItem'][]
      /** Subtotal Amount */
      subtotal_amount: number
      /** Discount Amount */
      discount_amount: number
      /** Discount Label */
      discount_label: string | null
      /** Tax Amount */
      tax_amount: number
      /** Total Amount */
      total_amount: number
      /** Checkout Link */
      checkout_link: string | null
      /** Memo */
      memo: string | null
    }
    /**
     * CommunityEmailOrgInfo
     * @description Subset of Organization the event emails actually render.
     *
     *     Stays flat + small so the customer_notifications payload (which
     *     persists with the bell row) doesn't carry the full ~30-field
     *     Organization schema. The header/footer components on the email
     *     side only consume name/slug/avatar/website.
     */
    CommunityEmailOrgInfo: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Slug */
      slug: string
      /**
       * Avatar Url
       * @default null
       */
      avatar_url: string | null
      /**
       * Website
       * @default null
       */
      website: string | null
    }
    /** CommunityEventAnnouncementEmail */
    CommunityEventAnnouncementEmail: {
      /**
       * Template
       * @default community_event_announcement
       * @constant
       */
      template: 'community_event_announcement'
      props: components['schemas']['CommunityEventAnnouncementProps']
    }
    /**
     * CommunityEventAnnouncementProps
     * @description Host-composed announcement on top of the standard event card.
     *
     *     Subject + body come straight from the composer modal; everything
     *     else (org, event, course_name, event_url) is identical to the
     *     auto-fired event emails so the recipient gets a consistent look.
     */
    CommunityEventAnnouncementProps: {
      /** Email */
      email: string
      organization: components['schemas']['CommunityEmailOrgInfo']
      /** Course Name */
      course_name: string
      /** Event Url */
      event_url: string
      event: components['schemas']['CommunityEventCardData']
      /** Subject */
      subject: string
      /** Body */
      body: string
      /** Host Name */
      host_name: string
    }
    /**
     * CommunityEventCardData
     * @description Presentational data the EventCard React Email component renders.
     *     Kept flat (no nested Event model) so the template can be invoked
     *     from any context — including bell rows whose stored payload doesn't
     *     have access to a live SQLAlchemy session.
     */
    CommunityEventCardData: {
      /** Title */
      title: string
      /** Type */
      type: string
      /** Start At */
      start_at: string
      /**
       * Timezone
       * @default UTC
       */
      timezone: string
      /** Duration Minutes */
      duration_minutes: number
      /** Host Name */
      host_name: string
      /**
       * Host Avatar Url
       * @default null
       */
      host_avatar_url: string | null
      /**
       * Cover Url
       * @default null
       */
      cover_url: string | null
      /**
       * Cover Object Position
       * @default null
       */
      cover_object_position: string | null
      /**
       * Location
       * @default null
       */
      location: string | null
      /**
       * Meeting Url
       * @default null
       */
      meeting_url: string | null
    }
    /** CommunityEventLiveEmail */
    CommunityEventLiveEmail: {
      /**
       * Template
       * @default community_event_live
       * @constant
       */
      template: 'community_event_live'
      props: components['schemas']['CommunityEventLiveProps']
    }
    /** CommunityEventLiveProps */
    CommunityEventLiveProps: {
      /** Email */
      email: string
      organization: components['schemas']['CommunityEmailOrgInfo']
      /** Course Name */
      course_name: string
      /** Event Url */
      event_url: string
      event: components['schemas']['CommunityEventCardData']
    }
    /** CommunityEventPublishedEmail */
    CommunityEventPublishedEmail: {
      /**
       * Template
       * @default community_event_published
       * @constant
       */
      template: 'community_event_published'
      props: components['schemas']['CommunityEventPublishedProps']
    }
    /** CommunityEventPublishedProps */
    CommunityEventPublishedProps: {
      /** Email */
      email: string
      organization: components['schemas']['CommunityEmailOrgInfo']
      /** Course Name */
      course_name: string
      /** Event Url */
      event_url: string
      event: components['schemas']['CommunityEventCardData']
      /** Host Name */
      host_name: string
    }
    /** CommunityEventRsvpConfirmedEmail */
    CommunityEventRsvpConfirmedEmail: {
      /**
       * Template
       * @default community_event_rsvp_confirmed
       * @constant
       */
      template: 'community_event_rsvp_confirmed'
      props: components['schemas']['CommunityEventRsvpConfirmedProps']
    }
    /** CommunityEventRsvpConfirmedProps */
    CommunityEventRsvpConfirmedProps: {
      /** Email */
      email: string
      organization: components['schemas']['CommunityEmailOrgInfo']
      /** Course Name */
      course_name: string
      /** Event Url */
      event_url: string
      event: components['schemas']['CommunityEventCardData']
    }
    /** CommunityEventStartingSoon24hEmail */
    CommunityEventStartingSoon24hEmail: {
      /**
       * Template
       * @default community_event_starting_soon_24h
       * @constant
       */
      template: 'community_event_starting_soon_24h'
      props: components['schemas']['CommunityEventStartingSoon24hProps']
    }
    /** CommunityEventStartingSoon24hProps */
    CommunityEventStartingSoon24hProps: {
      /** Email */
      email: string
      organization: components['schemas']['CommunityEmailOrgInfo']
      /** Course Name */
      course_name: string
      /** Event Url */
      event_url: string
      event: components['schemas']['CommunityEventCardData']
    }
    /**
     * CustomerCancellationReason
     * @enum {string}
     */
    CustomerCancellationReason:
      | 'customer_service'
      | 'low_quality'
      | 'missing_features'
      | 'switched_service'
      | 'too_complex'
      | 'too_expensive'
      | 'unused'
      | 'other'
    /** CustomerPortalSubscriptionSettings */
    CustomerPortalSubscriptionSettings: {
      /** Update Seats */
      update_seats: boolean
      /** Update Plan */
      update_plan: boolean
    }
    /** CustomerPortalUsageSettings */
    CustomerPortalUsageSettings: {
      /** Show */
      show: boolean
    }
    /** CustomerSessionCodeEmail */
    CustomerSessionCodeEmail: {
      /**
       * Template
       * @default customer_session_code
       * @constant
       */
      template: 'customer_session_code'
      props: components['schemas']['CustomerSessionCodeProps']
    }
    /** CustomerSessionCodeProps */
    CustomerSessionCodeProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      /** Code */
      code: string
      /** Code Lifetime Minutes */
      code_lifetime_minutes: number
      /** Url */
      url: string
    }
    /** EmailUpdateEmail */
    EmailUpdateEmail: {
      /**
       * Template
       * @default email_update
       * @constant
       */
      template: 'email_update'
      props: components['schemas']['EmailUpdateProps']
    }
    /** EmailUpdateProps */
    EmailUpdateProps: {
      /** Email */
      email: string
      /** Token Lifetime Minutes */
      token_lifetime_minutes: number
      /** Url */
      url: string
    }
    /** LoginCodeEmail */
    LoginCodeEmail: {
      /**
       * Template
       * @default login_code
       * @constant
       */
      template: 'login_code'
      props: components['schemas']['LoginCodeProps']
    }
    /** LoginCodeProps */
    LoginCodeProps: {
      /** Email */
      email: string
      /** Code */
      code: string
      /** Code Lifetime Minutes */
      code_lifetime_minutes: number
    }
    /** MaintainerAccountCreditsGrantedNotificationPayload */
    MaintainerAccountCreditsGrantedNotificationPayload: {
      /** Organization Name */
      organization_name: string
      /** Amount */
      amount: number
      /** Formatted Amount */
      readonly formatted_amount: string
    }
    /** MaintainerCreateAccountNotificationPayload */
    MaintainerCreateAccountNotificationPayload: {
      /** Organization Name */
      organization_name: string
      /** Url */
      url: string
    }
    /** MaintainerNewPaidSubscriptionNotificationPayload */
    MaintainerNewPaidSubscriptionNotificationPayload: {
      /** Subscriber Name */
      subscriber_name: string
      /** Tier Name */
      tier_name: string
      /** Tier Price Amount */
      tier_price_amount: number | null
      /** Tier Price Recurring Interval */
      tier_price_recurring_interval: string
      /** Tier Organization Name */
      tier_organization_name: string
      /**
       * Tier Organization Slug
       * @default null
       */
      tier_organization_slug: string | null
      /**
       * Subscription Id
       * @default null
       */
      subscription_id: string | null
      /** Formatted Price Amount */
      readonly formatted_price_amount: string
    }
    /** MaintainerNewProductSaleNotificationPayload */
    MaintainerNewProductSaleNotificationPayload: {
      /** Product Name */
      product_name: string
      /** Product Price Amount */
      product_price_amount: number
      /**
       * Customer Name
       * @default
       */
      customer_name: string
      /**
       * Organization Name
       * @default
       */
      organization_name: string
      /**
       * Customer Email
       * @default null
       */
      customer_email: string | null
      /**
       * Billing Address Country
       * @default null
       */
      billing_address_country: string | null
      /**
       * Billing Address City
       * @default null
       */
      billing_address_city: string | null
      /**
       * Billing Address Line1
       * @default null
       */
      billing_address_line1: string | null
      /**
       * Product Image Url
       * @default null
       */
      product_image_url: string | null
      /**
       * Order Id
       * @default null
       */
      order_id: string | null
      /**
       * Order Date
       * @default null
       */
      order_date: string | null
      /**
       * Organization Slug
       * @default null
       */
      organization_slug: string | null
      /** @default null */
      billing_reason: components['schemas']['OrderBillingReasonInternal'] | null
      /** Formatted Price Amount */
      readonly formatted_price_amount: string
      /** Formatted Billing Reason */
      readonly formatted_billing_reason: string | null
      /** Formatted Address Country */
      readonly formatted_address_country: string | null
      /** Order Url */
      readonly order_url: string | null
    }
    /** MarketingEmail */
    MarketingEmail: {
      /**
       * Template
       * @default marketing_email
       * @constant
       */
      template: 'marketing_email'
      props: components['schemas']['MarketingEmailProps']
    }
    /** MarketingEmailProps */
    MarketingEmailProps: {
      /** Organization Name */
      organization_name: string
      /**
       * Organization Logo Url
       * @default null
       */
      organization_logo_url: string | null
      /**
       * Organization Website
       * @default null
       */
      organization_website: string | null
      /** Html Content */
      html_content: string
      /** Unsubscribe Url */
      unsubscribe_url: string
      /**
       * Preview Text
       * @default null
       */
      preview_text: string | null
    }
    MetadataOutputType: {
      [key: string]: string | number | boolean
    }
    /** NotificationCreateAccountEmail */
    NotificationCreateAccountEmail: {
      /**
       * Template
       * @default notification_create_account
       * @constant
       */
      template: 'notification_create_account'
      props: components['schemas']['MaintainerCreateAccountNotificationPayload']
    }
    /** NotificationCreditsGrantedEmail */
    NotificationCreditsGrantedEmail: {
      /**
       * Template
       * @default notification_credits_granted
       * @constant
       */
      template: 'notification_credits_granted'
      props: components['schemas']['MaintainerAccountCreditsGrantedNotificationPayload']
    }
    /** NotificationNewSaleEmail */
    NotificationNewSaleEmail: {
      /**
       * Template
       * @default notification_new_sale
       * @constant
       */
      template: 'notification_new_sale'
      props: components['schemas']['MaintainerNewProductSaleNotificationPayload']
    }
    /** NotificationNewSubscriptionEmail */
    NotificationNewSubscriptionEmail: {
      /**
       * Template
       * @default notification_new_subscription
       * @constant
       */
      template: 'notification_new_subscription'
      props: components['schemas']['MaintainerNewPaidSubscriptionNotificationPayload']
    }
    /** OAuth2LeakedClientEmail */
    OAuth2LeakedClientEmail: {
      /**
       * Template
       * @default oauth2_leaked_client
       * @constant
       */
      template: 'oauth2_leaked_client'
      props: components['schemas']['OAuth2LeakedClientProps']
    }
    /** OAuth2LeakedClientProps */
    OAuth2LeakedClientProps: {
      /** Email */
      email: string
      /** Token Type */
      token_type: string
      /** Client Name */
      client_name: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** OAuth2LeakedTokenEmail */
    OAuth2LeakedTokenEmail: {
      /**
       * Template
       * @default oauth2_leaked_token
       * @constant
       */
      template: 'oauth2_leaked_token'
      props: components['schemas']['OAuth2LeakedTokenProps']
    }
    /** OAuth2LeakedTokenProps */
    OAuth2LeakedTokenProps: {
      /** Email */
      email: string
      /** Client Name */
      client_name: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /**
     * OrderBillingReason
     * @enum {string}
     */
    OrderBillingReason:
      | 'purchase'
      | 'subscription_create'
      | 'subscription_cycle'
      | 'subscription_update'
      | 'client_invoice'
    /**
     * OrderBillingReasonInternal
     * @description Internal billing reasons with additional granularity.
     * @enum {string}
     */
    OrderBillingReasonInternal:
      | 'purchase'
      | 'subscription_create'
      | 'subscription_cycle'
      | 'subscription_cycle_after_trial'
      | 'subscription_update'
      | 'client_invoice'
    /** OrderConfirmationEmail */
    OrderConfirmationEmail: {
      /**
       * Template
       * @default order_confirmation
       * @constant
       */
      template: 'order_confirmation'
      props: components['schemas']['OrderConfirmationProps']
    }
    /** OrderConfirmationProps */
    OrderConfirmationProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail'] | null
      order: components['schemas']['OrderEmail']
      /** Url */
      url: string
    }
    /** OrderEmail */
    OrderEmail: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the object.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /** @example paid */
      status: components['schemas']['OrderStatus']
      /**
       * Paid
       * @description Whether the order has been paid for.
       * @example true
       */
      paid: boolean
      /**
       * Subtotal Amount
       * @description Amount in cents, before discounts and taxes.
       * @example 10000
       */
      subtotal_amount: number
      /**
       * Discount Amount
       * @description Discount amount in cents.
       * @example 1000
       */
      discount_amount: number
      /**
       * Net Amount
       * @description Amount in cents, after discounts but before taxes.
       * @example 9000
       */
      net_amount: number
      /**
       * Tax Amount
       * @description Sales tax amount in cents.
       * @example 720
       */
      tax_amount: number
      /**
       * Total Amount
       * @description Amount in cents, after discounts and taxes.
       * @example 9720
       */
      total_amount: number
      /**
       * Applied Balance Amount
       * @description Customer's balance amount applied to this invoice. Can increase the total amount paid, if the customer has a negative balance,  or decrease it, if the customer has a positive balance.Amount in cents.
       * @example 0
       */
      applied_balance_amount: number
      /**
       * Due Amount
       * @description Amount in cents that is due for this order.
       * @example 0
       */
      due_amount: number
      /**
       * Refunded Amount
       * @description Amount refunded in cents.
       * @example 0
       */
      refunded_amount: number
      /**
       * Refunded Tax Amount
       * @description Sales tax refunded in cents.
       * @example 0
       */
      refunded_tax_amount: number
      /**
       * Currency
       * @example usd
       */
      currency: string
      billing_reason: components['schemas']['OrderBillingReason']
      /**
       * Billing Name
       * @description The name of the customer that should appear on the invoice.
       */
      billing_name: string | null
      billing_address: components['schemas']['Address'] | null
      /**
       * Invoice Number
       * @description The invoice number associated with this order.
       */
      invoice_number: string
      /**
       * Is Invoice Generated
       * @description Whether an invoice has been generated for this order.
       */
      is_invoice_generated: boolean
      /**
       * Seats
       * @description Number of seats purchased (for seat-based one-time orders).
       * @default null
       */
      seats: number | null
      /**
       * Customer Id
       * Format: uuid4
       */
      customer_id: string
      /** Product Id */
      product_id: string | null
      /** Discount Id */
      discount_id: string | null
      /** Subscription Id */
      subscription_id: string | null
      /** Checkout Id */
      checkout_id: string | null
      /** Description */
      description: string
      /** Items */
      items: components['schemas']['OrderItemSchema'][]
    }
    /**
     * OrderItemSchema
     * @description An order line item.
     */
    OrderItemSchema: {
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Id
       * Format: uuid4
       * @description The ID of the object.
       */
      id: string
      /**
       * Label
       * @description Description of the line item charge.
       * @example Pro Plan
       */
      label: string
      /**
       * Amount
       * @description Amount in cents, before discounts and taxes.
       * @example 10000
       */
      amount: number
      /**
       * Tax Amount
       * @description Sales tax amount in cents.
       * @example 720
       */
      tax_amount: number
      /**
       * Proration
       * @description Whether this charge is due to a proration.
       * @example false
       */
      proration: boolean
      /**
       * Product Price Id
       * @description Associated price ID, if any.
       */
      product_price_id: string | null
    }
    /**
     * OrderStatus
     * @enum {string}
     */
    OrderStatus: 'pending' | 'paid' | 'refunded' | 'partially_refunded'
    /** Organization */
    Organization: {
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Id
       * Format: uuid4
       * @description The ID of the object.
       */
      id: string
      /**
       * Name
       * @description Organization name shown in checkout, customer portal, emails etc.
       */
      name: string
      /**
       * Slug
       * @description Unique organization slug in checkout, customer portal and credit card statements.
       */
      slug: string
      /**
       * Avatar Url
       * @description Avatar URL shown in checkout, customer portal, emails etc.
       */
      avatar_url: string | null
      /**
       * Customer Portal Sign In Image Url
       * @description Image shown on the left panel of the customer portal sign-in screen. Configured from the course builder's Auth tab and applies to the whole organization's portal sign-in. When unset, the portal falls back to the organization's most recent course thumbnail.
       * @default null
       */
      customer_portal_sign_in_image_url: string | null
      /**
       * Customer Portal Sign In Image Position
       * @description CSS object-position (e.g. '50% 30%') for the customer portal sign-in image, set by dragging to reposition in the Auth tab.
       * @default null
       */
      customer_portal_sign_in_image_position: string | null
      /**
       * Customer Portal Sign In Theme
       * @description Creator-chosen appearance for the customer portal sign-in screen: 'light' or 'dark'. Null is treated as 'light'.
       * @default null
       */
      customer_portal_sign_in_theme: string | null
      /** @description Proration behavior applied when customer updates their subscription from the portal. */
      proration_behavior: components['schemas']['SubscriptionProrationBehavior']
      /**
       * Allow Customer Updates
       * @description Whether customers can update their subscriptions from the customer portal.
       */
      allow_customer_updates: boolean
      /**
       * Email
       * @description Public support email.
       */
      email: string | null
      /**
       * Website
       * @description Official website of the organization.
       */
      website: string | null
      /**
       * Socials
       * @description Links to social profiles.
       */
      socials: components['schemas']['OrganizationSocialLink'][]
      /** @description Current organization status */
      status: components['schemas']['OrganizationStatus']
      /**
       * Details Submitted At
       * @description When the business details were submitted.
       */
      details_submitted_at: string | null
      /**
       * Ai Onboarding Completed At
       * @description When the creator finished the onboarding flow (plan + review + assistant). Until this is set, the dashboard layout redirects the creator back to /onboarding/plan to prevent skipping the plan-selection step.
       * @default null
       */
      ai_onboarding_completed_at: string | null
      /** @description Default presentment currency. Used as fallback in checkout and customer portal, if the customer's local currency is not available. */
      default_presentment_currency: components['schemas']['PresentmentCurrency']
      /** @description Default tax behavior applied on products. */
      default_tax_behavior: components['schemas']['TaxBehaviorOption']
      /** @description Organization feature settings */
      feature_settings:
        | components['schemas']['OrganizationFeatureSettings']
        | null
      /** @description Settings related to subscriptions management */
      subscription_settings: components['schemas']['OrganizationSubscriptionSettings']
      /** @description Settings related to notifications */
      notification_settings: components['schemas']['OrganizationNotificationSettings']
      /** @description Settings related to customer emails */
      customer_email_settings: components['schemas']['OrganizationCustomerEmailSettings']
      /** @description Settings related to the customer portal */
      customer_portal_settings: components['schemas']['OrganizationCustomerPortalSettings']
      /**
       * @description Storefront settings
       * @default null
       */
      storefront_settings:
        | components['schemas']['OrganizationStorefrontSettings']
        | null
    }
    /** OrganizationAccessTokenLeakedEmail */
    OrganizationAccessTokenLeakedEmail: {
      /**
       * Template
       * @default organization_access_token_leaked
       * @constant
       */
      template: 'organization_access_token_leaked'
      props: components['schemas']['OrganizationAccessTokenLeakedProps']
    }
    /** OrganizationAccessTokenLeakedProps */
    OrganizationAccessTokenLeakedProps: {
      /** Email */
      email: string
      /** Organization Access Token */
      organization_access_token: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** OrganizationAccountUnlinkEmail */
    OrganizationAccountUnlinkEmail: {
      /**
       * Template
       * @default organization_account_unlink
       * @constant
       */
      template: 'organization_account_unlink'
      props: components['schemas']['OrganizationAccountUnlinkProps']
    }
    /** OrganizationAccountUnlinkProps */
    OrganizationAccountUnlinkProps: {
      /** Email */
      email: string
      /** Organization Kept Name */
      organization_kept_name: string
      /** Organizations Unlinked */
      organizations_unlinked: string[]
    }
    /** OrganizationCustomerEmailSettings */
    OrganizationCustomerEmailSettings: {
      /** Order Confirmation */
      order_confirmation: boolean
      /** Subscription Cancellation */
      subscription_cancellation: boolean
      /** Subscription Confirmation */
      subscription_confirmation: boolean
      /** Subscription Cycled */
      subscription_cycled: boolean
      /** Subscription Past Due */
      subscription_past_due: boolean
      /** Subscription Revoked */
      subscription_revoked: boolean
      /** Subscription Uncanceled */
      subscription_uncanceled: boolean
      /** Subscription Updated */
      subscription_updated: boolean
    }
    /** OrganizationCustomerPortalSettings */
    OrganizationCustomerPortalSettings: {
      usage: components['schemas']['CustomerPortalUsageSettings']
      subscription: components['schemas']['CustomerPortalSubscriptionSettings']
    }
    /** OrganizationFeatureSettings */
    OrganizationFeatureSettings: {
      /**
       * Issue Funding Enabled
       * @description If this organization has issue funding enabled
       * @default false
       */
      issue_funding_enabled: boolean
      /**
       * Seat Based Pricing Enabled
       * @description If this organization has seat-based pricing enabled
       * @default false
       */
      seat_based_pricing_enabled: boolean
      /**
       * Course Player White Label
       * @description When true, the course lesson player hides Spaire branding. Requires the white_label_course_player tier feature (Scale).
       * @default false
       */
      course_player_white_label: boolean
      /**
       * Revops Enabled
       * @description If this organization has RevOps enabled
       * @default false
       */
      revops_enabled: boolean
      /**
       * Wallets Enabled
       * @description If this organization has Wallets enabled
       * @default false
       */
      wallets_enabled: boolean
      /**
       * Member Model Enabled
       * @description If this organization has the Member model enabled
       * @default false
       */
      member_model_enabled: boolean
      /**
       * Tinybird Read
       * @description If this organization reads from Tinybird
       * @default false
       */
      tinybird_read: boolean
      /**
       * Tinybird Compare
       * @description If this organization compares Tinybird results with database
       * @default false
       */
      tinybird_compare: boolean
      /**
       * Perks Unlocked
       * @description If this organization has unlocked the Startup Stack perks by completing their first sale
       * @default false
       */
      perks_unlocked: boolean
    }
    /** OrganizationInviteEmail */
    OrganizationInviteEmail: {
      /**
       * Template
       * @default organization_invite
       * @constant
       */
      template: 'organization_invite'
      props: components['schemas']['OrganizationInviteProps']
    }
    /** OrganizationInviteProps */
    OrganizationInviteProps: {
      /** Email */
      email: string
      /** Organization Name */
      organization_name: string
      /** Inviter Email */
      inviter_email: string
      /** Invite Url */
      invite_url: string
    }
    /** OrganizationNotificationSettings */
    OrganizationNotificationSettings: {
      /** New Order */
      new_order: boolean
      /** New Subscription */
      new_subscription: boolean
    }
    /** OrganizationReviewedEmail */
    OrganizationReviewedEmail: {
      /**
       * Template
       * @default organization_reviewed
       * @constant
       */
      template: 'organization_reviewed'
      props: components['schemas']['OrganizationReviewedProps']
    }
    /** OrganizationReviewedProps */
    OrganizationReviewedProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
    }
    /** OrganizationSocialLink */
    OrganizationSocialLink: {
      /** @description The social platform of the URL */
      platform: components['schemas']['OrganizationSocialPlatforms']
      /**
       * Url
       * Format: uri
       * @description The URL to the organization profile
       */
      url: string
    }
    /**
     * OrganizationSocialPlatforms
     * @enum {string}
     */
    OrganizationSocialPlatforms:
      | 'x'
      | 'github'
      | 'facebook'
      | 'instagram'
      | 'youtube'
      | 'tiktok'
      | 'linkedin'
      | 'whatsapp'
      | 'spotify'
      | 'threads'
      | 'soundcloud'
      | 'snapchat'
      | 'pinterest'
      | 'patreon'
      | 'twitch'
      | 'apple_music'
      | 'website'
      | 'other'
    /**
     * OrganizationStatus
     * @enum {string}
     */
    OrganizationStatus:
      | 'created'
      | 'onboarding_started'
      | 'initial_review'
      | 'ongoing_review'
      | 'denied'
      | 'active'
    /** OrganizationStorefrontSettings */
    OrganizationStorefrontSettings: {
      /**
       * Enabled
       * @description Whether the storefront is enabled
       * @default false
       */
      enabled: boolean
      /**
       * Theme
       * @description Color theme for the public storefront
       * @default light
       * @enum {string}
       */
      theme: 'light' | 'dark'
      /**
       * Show Header
       * @description Show the storefront header/banner
       * @default true
       */
      show_header: boolean
      /**
       * Header Image Url
       * @description URL of the storefront header/banner image
       * @default null
       */
      header_image_url: string | null
      /**
       * Show Logo
       * @description Show the organization logo
       * @default true
       */
      show_logo: boolean
      /**
       * Show Name
       * @description Show the organization name
       * @default true
       */
      show_name: boolean
      /**
       * Show Description
       * @description Show the storefront description
       * @default true
       */
      show_description: boolean
      /**
       * Description
       * @description Storefront description
       * @default null
       */
      description: string | null
      /**
       * Meta Title
       * @description SEO title for the storefront — used as the page <title> and social card title. Falls back to the organization name.
       * @default null
       */
      meta_title: string | null
      /**
       * Meta Description
       * @description SEO meta description / social card summary. Falls back to the storefront description.
       * @default null
       */
      meta_description: string | null
      /**
       * Index
       * @description Allow search engines to index the storefront
       * @default true
       */
      index: boolean
      /**
       * Thumbnail Size
       * @description Product thumbnail size
       * @default large
       * @enum {string}
       */
      thumbnail_size: 'small' | 'medium' | 'large'
      /**
       * Show Product Details
       * @description Show product details (name, price)
       * @default true
       */
      show_product_details: boolean
      /**
       * Profile Title
       * @description Profile title (e.g. Designer, 3D Artist)
       * @default null
       */
      profile_title: string | null
      /**
       * Skills
       * @description Skill/expertise tags displayed on the profile
       */
      skills?: string[]
      /**
       * Languages
       * @description Languages spoken
       */
      languages?: string[]
      /**
       * Available For Work
       * @description Show 'Available for work' badge on the profile
       * @default false
       */
      available_for_work: boolean
      /**
       * Contact Url
       * @description Where the 'Available for work' badge sends visitors. Accepts an https:// URL (e.g. a contact form, calendar booking link) or a mailto: URL. When unset, the badge is non-interactive.
       * @default null
       */
      contact_url: string | null
      /**
       * Featured Mode
       * @description How to choose which products appear on the storefront. 'curated' (default) shows only the products the creator explicitly added via featured_product_ids. 'all' is a legacy mode that auto-shows every active product; kept so existing rows still validate.
       * @default curated
       * @enum {string}
       */
      featured_mode: 'all' | 'curated'
      /**
       * Featured Product Ids
       * @description Product IDs to feature on the storefront when featured_mode is 'curated'. Ignored when featured_mode is 'all'.
       */
      featured_product_ids?: string[]
      /**
       * Show Card Products
       * @description Show product images in the profile card
       * @default true
       */
      show_card_products: boolean
      /**
       * Storefront Links
       * @description Links displayed in a carousel on the storefront
       */
      storefront_links?: components['schemas']['StorefrontLink'][]
      /**
       * Links Position
       * @description DEPRECATED — use block_order. Where to show the links section relative to products. Kept so existing rows still validate.
       * @default after_products
       * @enum {string}
       */
      links_position: 'before_products' | 'after_products'
      /**
       * Block Order
       * @description Explicit ordering for the storefront's content blocks. The renderer iterates this list top-to-bottom, so creators can drag-reorder Products / Links / Forms freely. Backfilled from links_position for existing rows.
       */
      block_order?: ('products' | 'links' | 'forms')[]
      /**
       * Links Layout
       * @description Visual layout for the links section (default per-link layout)
       * @default classic
       * @enum {string}
       */
      links_layout: 'classic' | 'carousel' | 'image_grid' | 'card'
      /**
       * Header Focal Point
       * @description CSS object-position value for the cover image focal point (e.g. '50% 30%')
       * @default null
       */
      header_focal_point: string | null
      /**
       * Space Items
       * @description Flat ordered list of everything on the Space. When non-empty this is the single source of truth for the Space's render order — products and links interleave freely. When empty, the renderer falls back to deriving order from featured_product_ids + storefront_links + block_order for backwards compatibility with Spaces created before this model existed.
       */
      space_items?: components['schemas']['SpaceItem'][]
    }
    /** OrganizationSubscriptionSettings */
    OrganizationSubscriptionSettings: {
      /** Allow Multiple Subscriptions */
      allow_multiple_subscriptions: boolean
      /** Allow Customer Updates */
      allow_customer_updates: boolean
      proration_behavior: components['schemas']['SubscriptionProrationBehavior']
      /** Benefit Revocation Grace Period */
      benefit_revocation_grace_period: number
      /** Prevent Trial Abuse */
      prevent_trial_abuse: boolean
    }
    /** OrganizationUnderReviewEmail */
    OrganizationUnderReviewEmail: {
      /**
       * Template
       * @default organization_under_review
       * @constant
       */
      template: 'organization_under_review'
      props: components['schemas']['OrganizationUnderReviewProps']
    }
    /** OrganizationUnderReviewProps */
    OrganizationUnderReviewProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
    }
    /** PersonalAccessTokenLeakedEmail */
    PersonalAccessTokenLeakedEmail: {
      /**
       * Template
       * @default personal_access_token_leaked
       * @constant
       */
      template: 'personal_access_token_leaked'
      props: components['schemas']['PersonalAccessTokenLeakedProps']
    }
    /** PersonalAccessTokenLeakedProps */
    PersonalAccessTokenLeakedProps: {
      /** Email */
      email: string
      /** Personal Access Token */
      personal_access_token: string
      /** Notifier */
      notifier: string
      /** Url */
      url: string
    }
    /** PlatformReceiptEmail */
    PlatformReceiptEmail: {
      /**
       * Template
       * @default platform_receipt
       * @constant
       */
      template: 'platform_receipt'
      props: components['schemas']['PlatformReceiptProps']
    }
    /** PlatformReceiptProps */
    PlatformReceiptProps: {
      /** Email */
      email: string
      /** Plan Name */
      plan_name: string
      order: components['schemas']['OrderEmail']
      /** Url */
      url: string
    }
    /** PlatformWelcomeEmail */
    PlatformWelcomeEmail: {
      /**
       * Template
       * @default platform_welcome
       * @constant
       */
      template: 'platform_welcome'
      props: components['schemas']['PlatformWelcomeProps']
    }
    /** PlatformWelcomeProps */
    PlatformWelcomeProps: {
      /** Email */
      email: string
      /** Plan Name */
      plan_name: string
      /**
       * Trial End Date
       * @default null
       */
      trial_end_date: string | null
      /** Url */
      url: string
    }
    /**
     * PresentmentCurrency
     * @enum {string}
     */
    PresentmentCurrency:
      | 'aed'
      | 'all'
      | 'amd'
      | 'aoa'
      | 'ars'
      | 'aud'
      | 'awg'
      | 'azn'
      | 'bam'
      | 'bbd'
      | 'bdt'
      | 'bif'
      | 'bmd'
      | 'bnd'
      | 'bob'
      | 'brl'
      | 'bsd'
      | 'bwp'
      | 'bzd'
      | 'cad'
      | 'cdf'
      | 'chf'
      | 'clp'
      | 'cny'
      | 'cop'
      | 'crc'
      | 'cve'
      | 'czk'
      | 'djf'
      | 'dkk'
      | 'dop'
      | 'dzd'
      | 'egp'
      | 'etb'
      | 'eur'
      | 'fjd'
      | 'fkp'
      | 'gbp'
      | 'gel'
      | 'gip'
      | 'gmd'
      | 'gnf'
      | 'gtq'
      | 'gyd'
      | 'hkd'
      | 'hnl'
      | 'htg'
      | 'huf'
      | 'idr'
      | 'ils'
      | 'inr'
      | 'isk'
      | 'jmd'
      | 'jpy'
      | 'kes'
      | 'kgs'
      | 'khr'
      | 'kmf'
      | 'krw'
      | 'kyd'
      | 'kzt'
      | 'lak'
      | 'lkr'
      | 'lrd'
      | 'lsl'
      | 'mad'
      | 'mdl'
      | 'mga'
      | 'mkd'
      | 'mnt'
      | 'mop'
      | 'mur'
      | 'mvr'
      | 'mwk'
      | 'mxn'
      | 'myr'
      | 'mzn'
      | 'nad'
      | 'ngn'
      | 'nio'
      | 'nok'
      | 'npr'
      | 'nzd'
      | 'pab'
      | 'pen'
      | 'pgk'
      | 'php'
      | 'pkr'
      | 'pln'
      | 'pyg'
      | 'qar'
      | 'ron'
      | 'rsd'
      | 'rwf'
      | 'sar'
      | 'sbd'
      | 'scr'
      | 'sek'
      | 'sgd'
      | 'shp'
      | 'sos'
      | 'srd'
      | 'szl'
      | 'thb'
      | 'tjs'
      | 'top'
      | 'try'
      | 'ttd'
      | 'twd'
      | 'tzs'
      | 'uah'
      | 'ugx'
      | 'usd'
      | 'uyu'
      | 'uzs'
      | 'vnd'
      | 'vuv'
      | 'wst'
      | 'xaf'
      | 'xcd'
      | 'xcg'
      | 'xof'
      | 'xpf'
      | 'yer'
      | 'zar'
      | 'zmw'
    /**
     * ProductCategory
     * @enum {string}
     */
    ProductCategory:
      | 'ebook'
      | 'template'
      | 'assets'
      | 'course'
      | 'guide'
      | 'music'
      | 'video'
      | 'photo'
      | 'software'
      | 'coaching'
      | 'membership'
      | 'other'
    /** ProductEmail */
    ProductEmail: {
      /**
       * Id
       * Format: uuid4
       * @description The ID of the object.
       */
      id: string
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /** @description The interval unit for the trial period. */
      trial_interval: components['schemas']['TrialInterval'] | null
      /**
       * Trial Interval Count
       * @description The number of interval units for the trial period.
       */
      trial_interval_count: number | null
      /**
       * Name
       * @description The name of the product.
       */
      name: string
      /**
       * Description
       * @description The description of the product.
       */
      description: string | null
      /**
       * @description The digital product category.
       * @default null
       */
      category: components['schemas']['ProductCategory'] | null
      /** @description The visibility of the product. */
      visibility: components['schemas']['ProductVisibility']
      /** @description The recurring interval of the product. If `None`, the product is a one-time purchase. */
      recurring_interval:
        | components['schemas']['SubscriptionRecurringInterval']
        | null
      /**
       * Recurring Interval Count
       * @description Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on. None for one-time products.
       */
      recurring_interval_count: number | null
      /**
       * Is Recurring
       * @description Whether the product is a subscription.
       */
      is_recurring: boolean
      /**
       * Is Archived
       * @description Whether the product is archived and no longer available.
       */
      is_archived: boolean
      /**
       * Product Type
       * @description The type of product (e.g. 'digital', 'course').
       * @default digital
       */
      product_type: string
      /**
       * Organization Id
       * Format: uuid4
       * @description The ID of the organization owning the product.
       */
      organization_id: string
      /**
       * Benefits
       * @description List of benefits granted by the product.
       */
      benefits: components['schemas']['Benefit'][]
    }
    /**
     * ProductVisibility
     * @enum {string}
     */
    ProductVisibility: 'draft' | 'private' | 'public'
    /** SeatInvitationEmail */
    SeatInvitationEmail: {
      /**
       * Template
       * @default seat_invitation
       * @constant
       */
      template: 'seat_invitation'
      props: components['schemas']['SeatInvitationProps']
    }
    /** SeatInvitationProps */
    SeatInvitationProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      /** Product Name */
      product_name: string
      /** Billing Manager Email */
      billing_manager_email: string
      /** Claim Url */
      claim_url: string
    }
    /**
     * SpaceItem
     * @description A single entry in the Space's ordered list. The Space renders
     *     items in the order they appear in `space_items`; products and links
     *     can interleave freely (e.g. link → product → link → course → link).
     *     `kind` discriminates against ProductStorefront (`product`) vs a
     *     StorefrontLink already stored in `storefront_links` (`link`).
     *     `hidden` lets creators take an item off the Space without losing
     *     the item itself — products restore via the picker, links by
     *     flipping the flag.
     */
    SpaceItem: {
      /**
       * Kind
       * @description What `id` refers to: a product, a storefront_links entry, or a form.
       * @enum {string}
       */
      kind: 'product' | 'link' | 'form'
      /**
       * Id
       * @description Identifier of the referenced product or link.
       */
      id: string
      /**
       * Hidden
       * @description If true, the renderer skips this item. Lets creators hide an item without removing it from the Space's order or deleting it outright.
       * @default false
       */
      hidden: boolean
    }
    /** StorefrontLink */
    StorefrontLink: {
      /**
       * Id
       * @description Unique identifier for the link
       */
      id: string
      /**
       * Url
       * Format: uri
       * @description The URL of the link
       */
      url: string
      /**
       * Title
       * @description Display title for the link
       * @default null
       */
      title: string | null
      /**
       * Description
       * @description Short description shown on the card
       * @default null
       */
      description: string | null
      /**
       * Image Url
       * @description Thumbnail image URL for the link card
       * @default null
       */
      image_url: string | null
      /**
       * Type
       * @description Link type
       * @default standard
       * @enum {string}
       */
      type: 'standard' | 'embedded'
      /**
       * Platform
       * @description Detected platform (youtube, spotify, tiktok, soundcloud, instagram)
       * @default null
       */
      platform: string | null
      /**
       * Layout
       * @description Per-link visual layout (list / cards / grid / carousel). Embeds ignore this — they always render full-width. When unset, the link falls back to the section's links_layout.
       * @default null
       */
      layout: ('classic' | 'carousel' | 'image_grid' | 'card') | null
    }
    /** SubscriptionCancellationEmail */
    SubscriptionCancellationEmail: {
      /**
       * Template
       * @default subscription_cancellation
       * @constant
       */
      template: 'subscription_cancellation'
      props: components['schemas']['SubscriptionCancellationProps']
    }
    /** SubscriptionCancellationProps */
    SubscriptionCancellationProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail']
      subscription: components['schemas']['SubscriptionEmail']
      /** Url */
      url: string
    }
    /** SubscriptionConfirmationEmail */
    SubscriptionConfirmationEmail: {
      /**
       * Template
       * @default subscription_confirmation
       * @constant
       */
      template: 'subscription_confirmation'
      props: components['schemas']['SubscriptionConfirmationProps']
    }
    /** SubscriptionConfirmationProps */
    SubscriptionConfirmationProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail']
      subscription: components['schemas']['SubscriptionEmail']
      /** Url */
      url: string
      order: components['schemas']['OrderEmail']
    }
    /** SubscriptionCycledEmail */
    SubscriptionCycledEmail: {
      /**
       * Template
       * @default subscription_cycled
       * @constant
       */
      template: 'subscription_cycled'
      props: components['schemas']['SubscriptionCycledProps']
    }
    /** SubscriptionCycledProps */
    SubscriptionCycledProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail']
      subscription: components['schemas']['SubscriptionEmail']
      /** Url */
      url: string
      order: components['schemas']['OrderEmail']
    }
    /** SubscriptionEmail */
    SubscriptionEmail: {
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp of the object.
       */
      created_at: string
      /**
       * Modified At
       * @description Last modification timestamp of the object.
       */
      modified_at: string | null
      /**
       * Id
       * Format: uuid4
       * @description The ID of the object.
       */
      id: string
      /**
       * Amount
       * @description The amount of the subscription.
       * @example 10000
       */
      amount: number
      /**
       * Currency
       * @description The currency of the subscription.
       * @example usd
       */
      currency: string
      /**
       * @description The interval at which the subscription recurs.
       * @example month
       */
      recurring_interval: components['schemas']['SubscriptionRecurringInterval']
      /**
       * Recurring Interval Count
       * @description Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on.
       */
      recurring_interval_count: number
      /**
       * @description The status of the subscription.
       * @example active
       */
      status: components['schemas']['SubscriptionStatus']
      /**
       * Current Period Start
       * Format: date-time
       * @description The start timestamp of the current billing period.
       */
      current_period_start: string
      /**
       * Current Period End
       * @description The end timestamp of the current billing period.
       */
      current_period_end: string | null
      /**
       * Trial Start
       * @description The start timestamp of the trial period, if any.
       */
      trial_start: string | null
      /**
       * Trial End
       * @description The end timestamp of the trial period, if any.
       */
      trial_end: string | null
      /**
       * Cancel At Period End
       * @description Whether the subscription will be canceled at the end of the current period.
       */
      cancel_at_period_end: boolean
      /**
       * Canceled At
       * @description The timestamp when the subscription was canceled. The subscription might still be active if `cancel_at_period_end` is `true`.
       */
      canceled_at: string | null
      /**
       * Started At
       * @description The timestamp when the subscription started.
       */
      started_at: string | null
      /**
       * Ends At
       * @description The timestamp when the subscription will end.
       */
      ends_at: string | null
      /**
       * Ended At
       * @description The timestamp when the subscription ended.
       */
      ended_at: string | null
      /**
       * Customer Id
       * Format: uuid4
       * @description The ID of the subscribed customer.
       */
      customer_id: string
      /**
       * Product Id
       * Format: uuid4
       * @description The ID of the subscribed product.
       */
      product_id: string
      /**
       * Discount Id
       * @description The ID of the applied discount, if any.
       */
      discount_id: string | null
      /** Checkout Id */
      checkout_id: string | null
      /**
       * Seats
       * @description The number of seats for seat-based subscriptions. None for non-seat subscriptions.
       * @default null
       */
      seats: number | null
      customer_cancellation_reason:
        | components['schemas']['CustomerCancellationReason']
        | null
      /** Customer Cancellation Comment */
      customer_cancellation_comment: string | null
    }
    /** SubscriptionPastDueEmail */
    SubscriptionPastDueEmail: {
      /**
       * Template
       * @default subscription_past_due
       * @constant
       */
      template: 'subscription_past_due'
      props: components['schemas']['SubscriptionPastDueProps']
    }
    /** SubscriptionPastDueProps */
    SubscriptionPastDueProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail']
      subscription: components['schemas']['SubscriptionEmail']
      /** Url */
      url: string
      /**
       * Payment Url
       * @default null
       */
      payment_url: string | null
    }
    /**
     * SubscriptionProrationBehavior
     * @enum {string}
     */
    SubscriptionProrationBehavior: 'invoice' | 'prorate'
    /**
     * SubscriptionRecurringInterval
     * @enum {string}
     */
    SubscriptionRecurringInterval: 'day' | 'week' | 'month' | 'year'
    /** SubscriptionRevokedEmail */
    SubscriptionRevokedEmail: {
      /**
       * Template
       * @default subscription_revoked
       * @constant
       */
      template: 'subscription_revoked'
      props: components['schemas']['SubscriptionRevokedProps']
    }
    /** SubscriptionRevokedProps */
    SubscriptionRevokedProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail']
      subscription: components['schemas']['SubscriptionEmail']
      /** Url */
      url: string
    }
    /**
     * SubscriptionStatus
     * @enum {string}
     */
    SubscriptionStatus:
      | 'incomplete'
      | 'incomplete_expired'
      | 'trialing'
      | 'active'
      | 'past_due'
      | 'canceled'
      | 'unpaid'
    /** SubscriptionUncanceledEmail */
    SubscriptionUncanceledEmail: {
      /**
       * Template
       * @default subscription_uncanceled
       * @constant
       */
      template: 'subscription_uncanceled'
      props: components['schemas']['SubscriptionUncanceledProps']
    }
    /** SubscriptionUncanceledProps */
    SubscriptionUncanceledProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail']
      subscription: components['schemas']['SubscriptionEmail']
      /** Url */
      url: string
    }
    /** SubscriptionUpdatedEmail */
    SubscriptionUpdatedEmail: {
      /**
       * Template
       * @default subscription_updated
       * @constant
       */
      template: 'subscription_updated'
      props: components['schemas']['SubscriptionUpdatedProps']
    }
    /** SubscriptionUpdatedProps */
    SubscriptionUpdatedProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      product: components['schemas']['ProductEmail']
      subscription: components['schemas']['SubscriptionEmail']
      /** Url */
      url: string
      order: components['schemas']['OrderEmail'] | null
    }
    /**
     * TaxBehaviorOption
     * @enum {string}
     */
    TaxBehaviorOption: 'location' | 'inclusive' | 'exclusive'
    /**
     * TrialInterval
     * @enum {string}
     */
    TrialInterval: 'day' | 'week' | 'month' | 'year'
    /** UserWelcomeEmail */
    UserWelcomeEmail: {
      /**
       * Template
       * @default user_welcome
       * @constant
       */
      template: 'user_welcome'
      props: components['schemas']['UserWelcomeProps']
    }
    /** UserWelcomeProps */
    UserWelcomeProps: {
      /** Email */
      email: string
    }
    /** WebhookEndpointDisabledEmail */
    WebhookEndpointDisabledEmail: {
      /**
       * Template
       * @default webhook_endpoint_disabled
       * @constant
       */
      template: 'webhook_endpoint_disabled'
      props: components['schemas']['WebhookEndpointDisabledProps']
    }
    /** WebhookEndpointDisabledProps */
    WebhookEndpointDisabledProps: {
      /** Email */
      email: string
      organization: components['schemas']['Organization']
      /** Webhook Endpoint Url */
      webhook_endpoint_url: string
      /** Dashboard Url */
      dashboard_url: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
