export const SKILL_OPTIONS = [
  '2D Design',
  '3D Design',
  '3D Modeling',
  '2D Animation',
  '3D Animation',
  'Game Art',
  'Illustration',
  'Digital Art',
  'Graphic Design',
  'UI/UX Design',
  'Motion Graphics',
  'Video Editing',
  'Photography',
  'Ebook',
  'Templates',
  'Fonts',
  'Icons',
  'Mockups',
  'Textures',
  'Audio',
  'Music',
  'Sound Effects',
  'Presets',
  'LUTs',
  'Brushes',
  'Plugins',
  'WordPress Themes',
  'Notion Templates',
  'Figma',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'After Effects',
  'Blender',
  'Cinema 4D',
  'Unity',
  'Unreal Engine',
]

export const LANGUAGE_OPTIONS = [
  'English',
  'French',
  'Spanish',
  'German',
  'Portuguese',
  'Italian',
  'Dutch',
  'Russian',
  'Arabic',
  'Chinese',
  'Japanese',
  'Korean',
  'Hindi',
  'Turkish',
  'Polish',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Greek',
  'Czech',
  'Romanian',
  'Hungarian',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Malay',
  'Filipino',
  'Hebrew',
  'Ukrainian',
]

export const PROFILE_TITLE_OPTIONS = [
  'Designer',
  '3D Artist',
  'Illustrator',
  'Photographer',
  'Animator',
  'Video Editor',
  'Developer',
  'Writer',
  'Creator',
  'Music Producer',
  'Game Developer',
  'UI/UX Designer',
  'Graphic Designer',
  'Motion Designer',
]
