import { z } from 'zod'

export const outlineSchema = z.object({
  modules: z.array(
    z.object({
      title: z.string(),
      description: z.string().optional(),
      lessons: z.array(
        z.object({
          title: z.string(),
          // Lessons in AI-generated outlines are always video. Keep the field
          // for forward compatibility but constrain to a single value.
          content_type: z.literal('video'),
          // Short summary shown in lesson lists and headers.
          description: z.string().optional(),
          // Short body / script copy used to seed the lesson editor.
          content: z.string().optional(),
        }),
      ),
    }),
  ),
})

export type CourseOutline = z.infer<typeof outlineSchema>

// The full landing page is AI-generated. The UI only renders structure
// (layout, colors, typography) — every string below comes from the model.
//
// IMPORTANT: array fields are NOT bounded with min/max here on purpose. The
// `useObject` hook only fires onFinish once Zod validates the streamed JSON;
// strict cardinality on a streaming partial commonly stalls it. Cardinality
// is enforced in the prompt instead.
export const landingSchema = z.object({
  // Hero — note: hero "description" is NOT generated by the AI. It comes from
  // Step 2 of the wizard (course.desc / draft.desc) and is the canonical value
  // used everywhere the hero is rendered.
  eyebrow: z.string(),
  series_label: z.string(),
  tagline: z.string(),
  level: z.string(),

  // Value strip
  value_props_label: z.string(),
  value_props: z.array(
    z.object({
      title: z.string(),
      description: z.string(),
    }),
  ),

  // Curriculum
  curriculum_label: z.string(),
  curriculum_heading: z.string(),
  curriculum_subheading: z.string(),

  // Full lesson list
  lessons_label: z.string(),
  lessons_heading: z.string(),
  lessons_subheading: z.string(),

  // Instructor
  instructor_label: z.string(),
  instructor_pull_quote: z.string(),
  instructor_credentials: z.array(
    z.object({
      number: z.string(),
      label: z.string(),
    }),
  ),

  // Reviews
  reviews_label: z.string(),
  reviews: z.array(
    z.object({
      name: z.string(),
      role: z.string(),
      text: z.string(),
    }),
  ),

  // Final CTA
  final_cta_label: z.string(),
  final_cta_title: z.string(),
  final_cta_subtitle: z.string(),
  final_cta_primary: z.string(),
  final_cta_secondary: z.string(),
})

export type CourseLanding = z.infer<typeof landingSchema>
