"""Email segments: product FK changes from CASCADE to SET NULL

Revision ID: 7abe8ca7e3c9
Revises: cb9a8b32e09c
Create Date: 2026-05-17 12:00:00.000000

Previously deleting a product wiped every email segment scoped to it.
Segments are config — they should survive a product deletion as
orphans (product_id=NULL) so the operator can clean up or re-point
them rather than silently losing the segment definition entirely.

Postgres doesn't support ALTER CONSTRAINT for ondelete on FKs, so we
drop and recreate. The autogenerated constraint name is the default
``{table}_{column}_fkey`` shape.

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "7abe8ca7e3c9"
down_revision = "cb9a8b32e09c"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


_TABLE = "email_segments"
_FK_NAME = "email_segments_product_id_fkey"


def upgrade() -> None:
    op.drop_constraint(_FK_NAME, _TABLE, type_="foreignkey")
    op.create_foreign_key(
        _FK_NAME,
        _TABLE,
        "products",
        ["product_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(_FK_NAME, _TABLE, type_="foreignkey")
    op.create_foreign_key(
        _FK_NAME,
        _TABLE,
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
